name: 'Fetch WSUEs Data'
description: 'Fetch WSUEs data for specified date and products'
inputs:
  wsues-path:
    description: 'Path to WSUEs executable'
    required: true
  storage-path:
    description: 'Path to storage directory'
    required: true
  date:
    description: 'Date to fetch data for (YYYY-MM format)'
    required: true
  fetch-type:
    description: 'Type of fetch: single or all'
    required: true
    default: 'all'
  product:
    description: 'Product name (required for single fetch)'
    required: false
outputs:
  output-files:
    description: 'Path pattern to output files'
    value: ${{ steps.fetch.outputs.output-files }}

runs:
  using: 'composite'
  steps:
    - name: Fetch WSUEs data
      id: fetch
      shell: powershell
      run: |
        $wsuesExe = "${{ inputs.wsues-path }}\wsues.exe"
        $storagePath = "${{ inputs.storage-path }}"
        $date = "${{ inputs.date }}"
        $fetchType = "${{ inputs.fetch-type }}"
        
        Write-Host "🔄 Fetching WSUEs data..."
        Write-Host "  Date: $date"
        Write-Host "  Type: $fetchType"
        
        try {
          if ($fetchType -eq "single") {
            $product = "${{ inputs.product }}"
            if (-not $product) {
              Write-Error "Product is required for single fetch"
              exit 1
            }
            
            $outputFile = "$storagePath\$product.json"
            Write-Host "  Product: $product"
            Write-Host "  Output: $outputFile"
            
            & $wsuesExe get --date $date --product $product -o $outputFile
            
            if ($LASTEXITCODE -ne 0) {
              Write-Error "WSUEs fetch failed with exit code $LASTEXITCODE"
              exit 1
            }
            
            echo "output-files=$outputFile" >> $env:GITHUB_OUTPUT
            Write-Host "Single product fetch completed"
            
          } else {
            Write-Host "  Output directory: $storagePath"
            
            & $wsuesExe get-all --date $date -o $storagePath
            
            if ($LASTEXITCODE -ne 0) {
              Write-Error "WSUEs fetch-all failed with exit code $LASTEXITCODE"
              exit 1
            }
            
            # List generated files
            $jsonFiles = Get-ChildItem -Path $storagePath -Filter "*.json"
            Write-Host "Fetch-all completed. Generated files:"
            foreach ($file in $jsonFiles) {
              Write-Host "  - $($file.Name)"
            }
            
            echo "output-files=$storagePath\*.json" >> $env:GITHUB_OUTPUT
          }
          
        } catch {
          Write-Error "Fetch operation failed: $($_.Exception.Message)"
          exit 1
        }