name: WSUEs Fetch Workflow

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to fetch WSUEs for (YYYY-MM format)'
        required: true
        type: string
      fetch_type:
        description: 'Fetch type'
        type: choice
        required: true
        default: 'all'
        options:
          - 'single'
          - 'all'
      product:
        description: 'Product to fetch WSUEs for (only for single fetch)'
        type: choice
        required: false
        options:
          - 'Windows 10 21H2'
          - 'Windows 10 22H2'
          - 'Windows 11 22H2'
          - 'Windows 11 23H2'
          - 'Windows 11 24H2'
          - 'Windows Server 2019'
          - 'Windows Server 2022'
          - 'Windows Server 2025'
  schedule:
    - cron: '0 15 * * 2' # Every Tuesday at 15:00 UTC

permissions:
  contents: write
jobs:
  manual-fetch:
    name: Manual WSUEs Fetch
    runs-on: windows-2025 # todo: cannot use 2022 or latest, it's has issue when use wsues.
    if: github.event_name == 'workflow_dispatch'
    environment: WSUEs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup WSUEs
        id: setup
        uses: ./.github/actions/setup-wsues
        with:
          token: ${{ secrets.WSUESTOKEN }}
          workspace-path: ${{ github.workspace }}
          
      - name: Fetch WSUEs data
        id: fetch
        uses: ./.github/actions/fetch-wsues-data
        with:
          wsues-path: ${{ steps.setup.outputs.wsues-path }}
          storage-path: ${{ steps.setup.outputs.storage-path }}
          date: ${{ github.event.inputs.date }}
          fetch-type: ${{ github.event.inputs.fetch_type }}
          product: ${{ github.event.inputs.product }}
          
      - name: Compress files (for all products)
        id: compress
        if: github.event.inputs.fetch_type == 'all'
        uses: ./.github/actions/compress-files
        with:
          storage-path: ${{ steps.setup.outputs.storage-path }}
          
      - name: Upload artifacts (single product)
        if: github.event.inputs.fetch_type == 'single'
        uses: actions/upload-artifact@v4
        with:
          name: wsues-${{ github.event.inputs.product }}-${{ github.event.inputs.date }}
          path: ${{ steps.fetch.outputs.output-files }}
          retention-days: 30
          
      - name: Upload artifacts (all products)
        if: github.event.inputs.fetch_type == 'all'
        uses: actions/upload-artifact@v4
        with:
          name: wsues-all-${{ github.event.inputs.date }}
          path: ${{ steps.compress.outputs.compressed-pattern }}
          retention-days: 90
          
      - name: Create release (for all products)
        if: github.event.inputs.fetch_type == 'all'
        uses: ./.github/actions/create-release
        with:
          tag-name: ${{ github.event.inputs.date }}
          release-name: WSUEs ${{ github.event.inputs.date }}
          date: ${{ github.event.inputs.date }}
          files-pattern: ${{ steps.compress.outputs.compressed-pattern }}
          token: ${{ secrets.GITHUB_TOKEN }}

  scheduled-fetch:
    name: Scheduled WSUEs Fetch (Patch Tuesday)
    runs-on: windows-latest
    if: github.event_name == 'schedule'
    environment: WSUEs
    
    steps:
      - name: Check if today is Patch Tuesday
        id: patch-tuesday
        uses: ./.github/actions/check-patch-tuesday
        
      - name: Checkout repository
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: actions/checkout@v4
        
      - name: Setup WSUEs
        id: setup
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: ./.github/actions/setup-wsues
        with:
          token: ${{ secrets.WSUESTOKEN }}
          workspace-path: ${{ github.workspace }}
          
      - name: Fetch all WSUEs data
        id: fetch
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: ./.github/actions/fetch-wsues-data
        with:
          wsues-path: ${{ steps.setup.outputs.wsues-path }}
          storage-path: ${{ steps.setup.outputs.storage-path }}
          date: ${{ steps.patch-tuesday.outputs.current-date }}
          fetch-type: 'all'
          
      - name: Compress files
        id: compress
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: ./.github/actions/compress-files
        with:
          storage-path: ${{ steps.setup.outputs.storage-path }}
          
      - name: Upload artifacts
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: actions/upload-artifact@v4
        with:
          name: wsues-scheduled-${{ steps.patch-tuesday.outputs.current-date }}
          path: ${{ steps.compress.outputs.compressed-pattern }}
          retention-days: 90
          
      - name: Create release
        if: steps.patch-tuesday.outputs.is-patch-tuesday == 'True'
        uses: ./.github/actions/create-release
        with:
          tag-name: ${{ steps.patch-tuesday.outputs.current-date }}
          release-name: WSUEs ${{ steps.patch-tuesday.outputs.current-date }}
          date: ${{ steps.patch-tuesday.outputs.current-date }}
          files-pattern: ${{ steps.compress.outputs.compressed-pattern }}
          token: ${{ secrets.GITHUB_TOKEN }}
        