name: Manual WSUEs Pipeline
on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Date (YYYY-MM)'
        required: true
        type: string
      fetch_type:
        description: 'Type'
        type: choice
        required: true
        default: 'single'
        options:
          - 'single'
          - 'all'
      product:
        description: 'Product'
        type: choice
        required: false
        options:
          - 'Windows 10 21H2'
          - 'Windows 10 22H2'
          - 'Windows 11 22H2'
          - 'Windows 11 23H2'
          - 'Windows 11 24H2'
          - 'Windows Server 2019'
          - 'Windows Server 2022'
          - 'Windows Server 2025'

permissions:
  contents: write
jobs:
  manual-fetch:
    name: Manual WSUEs Fetch
    runs-on: windows-2025 # !important
    environment: WSUEs
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup WSUEs
        id: setup
        uses: ./.github/actions/setup-wsues
        with:
          token: ${{ secrets.WSUESTOKEN }}
          workspace-path: ${{ github.workspace }}
          
      - name: Fetch WSUEs data
        id: fetch
        uses: ./.github/actions/fetch-wsues-data
        with:
          wsues-path: ${{ steps.setup.outputs.wsues-path }}
          storage-path: ${{ steps.setup.outputs.storage-path }}
          date: ${{ github.event.inputs.date }}
          fetch-type: ${{ github.event.inputs.fetch_type }}
          product: ${{ github.event.inputs.product }}
          
      - name: Compress files
        id: compress
        if: github.event.inputs.fetch_type == 'all'
        uses: ./.github/actions/compress-files
        with:
          storage-path: ${{ steps.setup.outputs.storage-path }}
          
      - name: Upload artifacts (single)
        if: github.event.inputs.fetch_type == 'single'
        uses: actions/upload-artifact@v4
        with:
          name: wsues-${{ github.event.inputs.product }}-${{ github.event.inputs.date }}
          path: ${{ steps.fetch.outputs.output-files }}
          retention-days: 30
          
      - name: Upload artifacts (all)
        if: github.event.inputs.fetch_type == 'all'
        uses: actions/upload-artifact@v4
        with:
          name: wsues-all-${{ github.event.inputs.date }}
          path: ${{ steps.compress.outputs.compressed-pattern }}
          retention-days: 90
          
      - name: Create release (all)
        if: github.event.inputs.fetch_type == 'all'
        uses: ./.github/actions/create-release
        with:
          tag-name: ${{ github.event.inputs.date }}
          release-name: WSUEs ${{ github.event.inputs.date }}
          date: ${{ github.event.inputs.date }}
          files-pattern: ${{ steps.compress.outputs.compressed-pattern }}
          token: ${{ secrets.GITHUB_TOKEN }}
